### ISSUE TITLE
WP_Feedback_Data Must be Sanitized, Escaped, and Validated

### ISSUE THREAD

**Issue by JonathanPultz** [mondula/ticket-hub#15]
When you include POST/GET/REQUEST/FILE calls in your plugin, it's important to sanitize, validate, and escape them. The goal here is to prevent a user from accidentally sending trash data through the system, as well as protecting them from potential security issues.

**SANITIZE**: Data that is input (either by a user or automatically) must be sanitized as soon as possible. This lessens the possibility of XSS vulnerabilities and MITM attacks where posted data is subverted.

**VALIDATE**: All data should be validated, no matter what. Even when you sanitize, remember that you don’t want someone putting in ‘dog’ when the only valid values are numbers.

**ESCAPE**: Data that is output must be escaped properly when it is echo'd, so it can't hijack admin screens. There are many esc_*() functions you can use to make sure you don't show people the wrong data.

To help you with this, WordPress comes with a number of sanitization and escaping functions. You can read about those here:

https://developer.wordpress.org/apis/security/sanitizing/
https://developer.wordpress.org/apis/security/escaping/

Remember: You must use the most appropriate functions for the context. If you’re sanitizing email, use sanitize_email(), if you’re outputting HTML, use wp_kses_post(), and so on.

An easy mantra here is this:

_Sanitize early
Escape Late
Always Validate_

Clean everything, check everything, escape everything, and never trust the users to always have input sane data. After all, users come from all walks of life.

Example(s) from your plugin:

ticket-hub/includes/th-ticket-creators-tab.php:22 if ($_SERVER['REQUEST_METHOD'] == 'POST' && isset($_POST['create_user_nonce']) && wp_verify_nonce($_POST['create_user_nonce'], 'create_th_ticket_creator')) {
 -----> wp_verify_nonce($_POST['create_user_nonce'], 'create_th_ticket_creator')
ticket-hub/shortcodes/th-form-sc.php:73 if (!isset($_POST['ticket_nonce_field']) || !wp_verify_nonce($_POST['ticket_nonce_field'], 'submit_ticket_nonce')) {
ticket-hub/post-types/th-change-pt.php:75 if (!isset($_POST['th_log_meta_nonce']) || !wp_verify_nonce($_POST['th_log_meta_nonce'], 'th_save_log_meta')) {
ticket-hub/post-types/th-document-pt.php:135 if (!isset($_POST['th_document_fields_nonce']) || !wp_verify_nonce($_POST['th_document_fields_nonce'], basename(__FILE__))) {
ticket-hub/post-types/th-faq-pt.php:74 if (!isset($_POST['th_answer_meta_nonce']) || !wp_verify_nonce($_POST['th_answer_meta_nonce'], 'th_save_answer_meta')) {
ticket-hub/shortcodes/th-form-sc.php:77 $attachments = $_FILES['your-attachments'];
ticket-hub/includes/th-form-editor-tab.php:11 $options_list = isset($_POST['input_options']) ? $_POST['input_options'] : [];
ticket-hub/post-types/th-ticket-pt.php:204 if (!isset($_POST['ticket_meta_nonce']) || !wp_verify_nonce($_POST['ticket_meta_nonce'], 'save_ticket_meta')) return;

**Note**: When checking a nonce using wp_verify_nonce you will need to sanitize the input using wp_unslash AND sanitize_text_field, [this is because this function is pluggable, and extenders should not trust its input values.](https://developer.wordpress.org/news/2023/08/01/understand-and-use-wordpress-nonces-properly/#verifying-the-nonce)

Example:
if ( ! isset( $_POST['prefix_nonce'] ) || ! wp_verify_nonce( sanitize_text_field( wp_unslash ( $_POST['prefix_nonce'] ) ) , 'prefix_nonce' ) )

Example(s) from your plugin:

ticket-hub/includes/th-ticket-creators-tab.php:22 if ($_SERVER['REQUEST_METHOD'] == 'POST' && isset($_POST['create_user_nonce']) && wp_verify_nonce($_POST['create_user_nonce'], 'create_th_ticket_creator')) {
 -----> wp_verify_nonce($_POST['create_user_nonce'], 'create_th_ticket_creator')
ticket-hub/post-types/th-ticket-pt.php:204 if (!isset($_POST['ticket_meta_nonce']) || !wp_verify_nonce($_POST['ticket_meta_nonce'], 'save_ticket_meta')) return;
ticket-hub/post-types/th-faq-pt.php:74 if (!isset($_POST['th_answer_meta_nonce']) || !wp_verify_nonce($_POST['th_answer_meta_nonce'], 'th_save_answer_meta')) {
ticket-hub/post-types/th-document-pt.php:135 if (!isset($_POST['th_document_fields_nonce']) || !wp_verify_nonce($_POST['th_document_fields_nonce'], basename(__FILE__))) {

... out of a total of 6 incidences.

**Comment by KamiCasi** [comment]
sanitize_text_field( wp_unslash ( )) eingefügt bei:
```

- ticket-hub/includes/th-ticket-creators-tab.php:22 if ($_SERVER['REQUEST_METHOD'] == 'POST' && isset($_POST['create_user_nonce']) && wp_verify_nonce($_POST['create_user_nonce'], 'create_th_ticket_creator')) {
-----> wp_verify_nonce($_POST['create_user_nonce'], 'create_th_ticket_creator')
- ticket-hub/shortcodes/th-form-sc.php:73 if (!isset($_POST['ticket_nonce_field']) || !wp_verify_nonce($_POST['ticket_nonce_field'], 'submit_ticket_nonce')) {
- ticket-hub/post-types/th-change-pt.php:75 if (!isset($_POST['th_log_meta_nonce']) || !wp_verify_nonce($_POST['th_log_meta_nonce'], 'th_save_log_meta')) {
- ticket-hub/post-types/th-document-pt.php:135 if (!isset($_POST['th_document_fields_nonce']) || !wp_verify_nonce($_POST['th_document_fields_nonce'], basename(FILE))) {
- ticket-hub/post-types/th-faq-pt.php:74 if (!isset($_POST['th_answer_meta_nonce']) || !wp_verify_nonce($_POST['th_answer_meta_nonce'], 'th_save_answer_meta')) {
- ticket-hub/post-types/th-ticket-pt.php:204 if (!isset($_POST['ticket_meta_nonce']) || !wp_verify_nonce($_POST['ticket_meta_nonce'], 'save_ticket_meta')) return;

```

sanitize_file_name() bei:
`ticket-hub/shortcodes/th-form-sc.php:77 $attachments = $_FILES['your-attachments'];`

sanitize_text_field() bei:
`ticket-hub/includes/th-form-editor-tab.php:11 $options_list = isset($_POST['input_options']) ? $_POST['input_options'] : [];`
